version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "binco97/solidarity-purchasing-group-backend"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "binco97/solidarity-purchasing-group-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"